### ISSUE TITLE
File header clarifications

### ISSUE THREAD

**Issue by jnumm** [shlomif/pysol_cards#2]
pysol_cards/tests/test_pysol_cards.py does not have author info. It should preferably have a copyright line with your name & email. [Debian wiki's upstream guide](https://wiki.debian.org/UpstreamGuide#Licenses) asks software authors to “document copyright attribution in each file.” This file also has a Apache-2.0 license while most other code files are MIT/Expat licensed.

setup.py line 16 claims it should not be edited which probably is not the case here.

**Comment by shlomif** [comment]
should be fixed in 0.8.8. Thanks!

**Comment by jnumm** [comment]
Ok, thanks!
