### ISSUE TITLE
0.14.2: pytest is using `random2` which not maintained

### ISSUE THREAD

**Issue by kloczek** [shlomif/pysol_cards#5]
pytest is using `random2` which not maintained since 2013 https://github.com/joke2k/faker/issues/1635
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pysol-cards-0.14.2-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pysol-cards-0.14.2-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pysol_cards-0.14.2, configfile: setup.cfg
plugins: anyio-3.5.0, cov-3.0.0, socket-0.5.1, tornasync-0.6.0.post2
collected 7 items / 1 error

================================================================================== ERRORS ==================================================================================
________________________________________________________________ ERROR collecting tests/test_pysol_cards.py ________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/pysol_cards-0.14.2/tests/test_pysol_cards.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pysol_cards.py:19: in <module>
    import pysol_cards.random
pysol_cards/random.py:14: in <module>
    import random2
E   ModuleNotFoundError: No module named 'random2'

---------- coverage: platform linux, python 3.8.13-final-0 -----------
Name                                    Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------------------
pysol_cards/__init__.py                     8      0      0      0   100%
pysol_cards/__main__.py                     8      8      2      0     0%   7-25
pysol_cards/cards.py                       55     37     24      0    28%   19-20, 23, 26, 29, 32-34, 40, 43-48, 51, 54-57, 60, 63, 67-74, 78-84
pysol_cards/deal_game.py                  263    263    125      0     0%   8-368
pysol_cards/errors.py                       2      0      2      0   100%
pysol_cards/random.py                     104    100     30      0     3%   17-167
pysol_cards/random_base.py                 54     27      8      0    47%   26, 29-32, 36, 40, 44, 47, 50-52, 55, 58, 61, 64-66, 69-71, 74, 77-79, 83, 87
pysol_cards/single_deal_args_parse.py      29     29     16      0     0%   8-46
pysol_cards/template.py                     2      0      0      0   100%
-----------------------------------------------------------------------------------
TOTAL                                     525    464    207      0     9%

========================================================================= short test summary info ==========================================================================
ERROR tests/test_pysol_cards.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.17s =============================================================================
```

**Comment by shlomif** [comment]
Hi Tomasz!

On Tue, 10 May 2022 23:03:09 -0700
Tomasz Kłoczko ***@***.***> wrote:

> pytest is using `random2` which not maintained since 2013
> https://github.com/joke2k/faker/issues/1635 ```console
> +
> PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pysol-cards-0.14.2-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pysol-cards-0.14.2-3.fc35.x86_64/usr/lib/python3.8/site-packages
> + /usr/bin/pytest -ra
> ===========================================================================
> test session starts
> ============================================================================

See https://perl.plover.com/yak/12views/samples/notes.html#sl-9 . PySol
FC-compatible cards dealing assumes random2.py's semantics [and random2 works
fine in py3]

> platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 rootdir:
> /home/tkloczko/rpmbuild/BUILD/pysol_cards-0.14.2, configfile: setup.cfg
> plugins: anyio-3.5.0, cov-3.0.0, socket-0.5.1, tornasync-0.6.0.post2
> collected 7 items / 1 error
> 
> ==================================================================================
> ERRORS
> ==================================================================================
> ________________________________________________________________ ERROR
> collecting tests/test_pysol_cards.py
> ________________________________________________________________ ImportError
> while importing test module
> '/home/tkloczko/rpmbuild/BUILD/pysol_cards-0.14.2/tests/test_pysol_cards.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback: /usr/lib64/python3.8/importlib/__init__.py:127: in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> tests/test_pysol_cards.py:19: in <module> import pysol_cards.random
> pysol_cards/random.py:14: in <module> import random2 E   ModuleNotFoundError:
> No module named 'random2'
> 
> ---------- coverage: platform linux, python 3.8.13-final-0 -----------
> Name                                    Stmts   Miss Branch BrPart  Cover
> Missing
> -----------------------------------------------------------------------------------
> pysol_cards/__init__.py                     8      0      0      0   100%
> pysol_cards/__main__.py                     8      8      2      0     0%
> 7-25 pysol_cards/cards.py                       55     37     24      0
> 28%   19-20, 23, 26, 29, 32-34, 40, 43-48, 51, 54-57, 60, 63, 67-74, 78-84
> pysol_cards/deal_game.py                  263    263    125      0     0%
> 8-368 pysol_cards/errors.py                       2      0      2      0
> 100% pysol_cards/random.py                     104    100     30      0
> 3%   17-167 pysol_cards/random_base.py                 54     27      8
> 0    47%   26, 29-32, 36, 40, 44, 47, 50-52, 55, 58, 61, 64-66, 69-71, 74,
> 77-79, 83, 87 pysol_cards/single_deal_args_parse.py      29     29     16
>  0     0%   8-46 pysol_cards/template.py                     2      0      0
>     0   100%
> -----------------------------------------------------------------------------------
> TOTAL                                     525    464    207      0     9%
> 
> =========================================================================
> short test summary info
> ==========================================================================
> ERROR tests/test_pysol_cards.py
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Interrupted: 1 error during collection
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> =============================================================================
> 1 error in 0.17s
> =============================================================================
> ```
> 
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Perl Humour - https://perl-begin.org/humour/

E‐mail, web feeds, and doing something productive — choose two.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by kloczek** [comment]
It maybe work but python provides OOTB `random` module.

**Comment by shlomif** [comment]
Hi!

On Wed, 11 May 2022 09:47:04 -0700
Tomasz Kłoczko ***@***.***> wrote:

> It maybe work but python provides OOTB `random` module.
> 

I am aware of it, but when using it, different cards are being dealt than those
which were origly dealt, due2a random.py changeofbehaviour.


-- 

Shlomi Fish       https://www.shlomifish.org/
Free (Creative Commons) Music Downloads, Reviews and more - https://jamendo.com/

“THERE IS NO JUSTICE. THERE’S ONLY ME.“
    — Death in Terry Pratchett’s Mort

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
closing as REJECTED.

**Comment by kloczek** [comment]
Any rational reason to not use standard `random` python library? 🤔 
`randon2` is not only dependent in tesst suite. It is as well install-time dependency as well.

**Comment by shlomif** [comment]
> Any rational reason to not use standard `random` python library? thinking `randon2` is not only dependent in tesst suite. It is as well install-time dependency as well.

Oh, For fuck's sake. I've explained it above.

**Comment by kloczek** [comment]
> Oh, For fuck's sake. I've explained it above.

No you did not.
So you mean `random` API changes?
So how many times since 2013 that module API changed and if it where some changes why not follow those changes? 🤔
