### ISSUE TITLE
Saving/retrieving random state does not work

### ISSUE THREAD

**Issue by joeraz** [shlomif/pysol_cards#7]
In PySolFC, the random object's setstate and getstate functions are used to save and restore the state of the random number generator.  This is done prior to a move that involves reshuffling cards (such as in Montana or La Belle Lucie), so if an undo and then a redo is used on the reshuffle move, the cards will be reshuffled in the same manner both times.

The code for this can be seen at https://github.com/shlomif/PySolFC/blob/ef404e3fc16ea132ad969f7acb730e78387da50e/pysollib/move.py#L449

However, the setstate and getstate methods do not appear to be working correctly.  While I can see state values being saved and re-retrieved, they don't appear to have any effect on the random shuffling.  Also, it doesn't look like getstate has an initial value if no state has been set yet.  

See https://github.com/shlomif/PySolFC/issues/278 for the original issue.

**Comment by shlomif** [comment]
hi Joe,

On Sat, 17 Dec 2022 13:08:21 -0800
"Joe R." ***@***.***> wrote:

> In PySolFC, the random object's setstate and getstate functions are used to
> save and restore the state of the random number generator.  This is done
> prior to a move that involves reshuffling cards (such as in Montana or La
> Belle Lucie), so if an undo and then a redo is used on the reshuffle move,
> the cards will be reshuffled in the same manner both times.
> 
> The code for this can be seen at
> https://github.com/shlomif/PySolFC/blob/ef404e3fc16ea132ad969f7acb730e78387da50e/pysollib/move.py#L449
> 
> However, the setstate and getstate methods do not appear to be working
> correctly.  While I can see state values being saved and re-retrieved, they
> don't appear to have any effect on the random shuffling.  Also, it doesn't
> look like getstate has an initial value if no state has been set yet.  
> 
> See https://github.com/shlomif/PySolFC/issues/278 for the original issue.
> 

thanks, but please write a patch or pull-req that adds a failing automated test.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/KNvczZ - The FSF Announces New Versions of the GPL

As every cat owner knows, nobody owns a cat.
    — Source unknown, via Nadav Har’El.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@joeraz : ping

**Comment by joeraz** [comment]
Thanks for the ping.  Working on that - sorry, got a little sidetracked with the holidays.

**Comment by shlomif** [comment]
On Sat, 07 Jan 2023 11:04:36 -0800
"Joe R." ***@***.***> wrote:

> Thanks for the ping.  Working on that - sorry, got a little sidetracked with
> the holidays.
> 

Ack.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://shlomifishswiki.branchable.com/Self-Sufficiency/

Chuck Norris knows exactly which thing is rotten in the kingdom of Denmark.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@joeraz : hi, see the latest commits

**Comment by joeraz** [comment]
Okay, will test and confirm.

**Comment by joeraz** [comment]
So the unit tests pass for me when I ran them the other day, but I'm having a little trouble getting the updated version configured to run against actual PySolFC to see if this fixes the issue there.  I'll have to sort out a few things in my local dev environment and get back to you on that one.

**Comment by shlomif** [comment]
On Tue, 10 Jan 2023 20:14:36 -0800
"Joe R." ***@***.***> wrote:

> So the unit tests pass for me when I ran them the other day, but I'm having a
> little trouble getting the updated version configured to run against actual
> PySolFC to see if this fixes the issue there.  I'll have to sort out a few
> things in my local dev environment and get back to you on that one.
> 

thx4the headsup.

-- 

Shlomi Fish       https://www.shlomifish.org/
Funny Anti-Terrorism Story - https://shlom.in/enemy

To [presumably] quote Kahless the Unforgettable: “Only the most timid of
warriors shall attempt to evade an opportunity of peaceful enlightenment.”. We
have no intention to escape, and surely you can outrun… or outfly us.
    — https://is.gd/zfQlsH

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
Alright, saving the state is working correctly now in PySolFC.

The change seems to have caused a couple issues with loading of old saves on the PySolFC side, but I'll review that on the PySolFC side.  All good here for now.

**Comment by shlomif** [comment]
On Thu, 12 Jan 2023 17:45:57 -0800
"Joe R." ***@***.***> wrote:

> Alright, saving the state is working correctly now in PySolFC.
> 
> The change seems to have caused a couple issues with loading of old saves on
> the PySolFC side, but I'll review that on the PySolFC side.  All good here
> for now.
> 

thanks, Joe!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Emma-Watson/

“I don't want to mess with Summer Glau, but I'll let her mess with me every
day!”
    — https://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
